Book store category
hanshyn/online-book-store pull request #10
Opened 2024-01-24 09:48 UTC by hanshyn

Added:
 * Category entity
 * Category DTO
 * Category Repository
 * Category Mapper
 * Category Conntroller

2024-01-24 19:25 UTC, olekskov requested changes

2024-01-24 19:25 UTC, olekskov commented on src/main/java/hanshyn/onlinebookstore/controller/CategoryController.java
> +    @PreAuthorize("hasAnyAuthority('ROLE_USER', 'ROLE_ADMIN')")
You have .anyRequest().authenticated() in your config
This means that unauthorized user cannot access this endpoint. So if user with any tole may access then there is no need to mention them all.
We put annotation only if we want not all of our roles to have access
```suggestion
```
Please recheck all occurences

2024-01-25 11:33 UTC, kozhukhovsky approved these changes

2024-01-25 11:33 UTC, kozhukhovsky commented on src/main/java/hanshyn/onlinebookstore/controller/CategoryController.java
> +
```suggestion
```

2024-01-25 17:49 UTC, merged