Added ShoppingCart, CartItems entity and methods
hanshyn/online-book-store pull request #11
Opened 2024-02-10 14:47 UTC by hanshyn

Shopping Cart Management:

As a User, I want to add books to my shopping cart, so I can purchase them. I will:
Send a POST request to /api/cart to add a book to the shopping cart.
As a User, I want to view my shopping cart, so I can review its contents before placing an order. I will:
Send a GET request to /api/cart to retrieve my shopping cart.
As a User, I want to update the books quantity in my shopping cart, so I can update my intended purchases. I will:
Send a PUT request to /api/cart/cart-items/{cartItemId} to update the books quantity in the shopping cart.
As a User, I want to remove books from my shopping cart, so I can update my intended purchases. I will:
Send a DELETE request to /api/cart/cart-items/{cartItemId} to remove a book from the shopping cart.

2024-02-10 16:56 UTC, olekskov requested changes

2024-02-10 16:56 UTC, olekskov commented on src/main/java/hanshyn/onlinebookstore/service/cart/ShoppingCartServiceImpl.java
> +        User user = (User) authentication.getPrincipal();
1) For me it's better to leave work with authentication on controller level and let service work with entity required
2) Several DB modifications inside method, without proper annotation we may loose consistency of data in DB
```suggestion
    @Override
    @Transactional
    public CartItemsResponseDto saveBookToShoppingCart(User user,
                                                       CartItemsRequestDto cartItemsRequestDto) {
```

2024-02-10 16:56 UTC, olekskov commented on src/main/java/hanshyn/onlinebookstore/service/cart/ShoppingCartServiceImpl.java
> +                .orElseGet(() -> createNewShoppingCart(user));
Sorry, but I cannot understand logic.
If we try to get ShoppingCart and haven't found it we throw exception. But if we adding item and haven't found cart we create it.
How should get operation work before first insert?

In general: shop is place where we need users in order them to buy something. User without cart has no any value.
For me it's more logical to create cart during registration process and assume that it's exist by default and handle case when cart wasn't found as some data integrity violation

2024-02-10 16:56 UTC, olekskov commented on src/main/java/hanshyn/onlinebookstore/service/cart/ShoppingCartServiceImpl.java
> +    }
On add operation you check user that is authenticated but on update/delete you allow anyone to modify other user's cart. 
E.g. I'm user 1 and have items 1, 2 and 3 in my cart. I'm sending request to delete cart-item with id 4. Then you will delete it for some other user obviously

2024-02-11 18:37 UTC, okuzan requested changes

2024-02-11 18:37 UTC, okuzan commented on src/main/java/hanshyn/onlinebookstore/mapper/CartItemMapper.java
> +
```suggestion
```

2024-02-11 18:37 UTC, okuzan commented on src/main/java/hanshyn/onlinebookstore/model/ShoppingCart.java
> +@Where(clause = "is_deleted = false")
```suggestion
@SQLDelete(sql = "UPDATE shopping_cart SET is_deleted = TRUE WHERE id = ?")
@Where(clause = "is_deleted = FALSE")
```

2024-02-11 18:37 UTC, okuzan commented on src/main/java/hanshyn/onlinebookstore/service/cart/ShoppingCartService.java
> +                                        CartItemsUpdateRequestDto cartItemsUpdateRequestDto,
```suggestion
    CartItemsResponseDto updateQuantity(CartItemsUpdateRequestDto cartItemsUpdateRequestDto,
```

2024-02-11 18:37 UTC, okuzan commented on src/main/java/hanshyn/onlinebookstore/service/cart/ShoppingCartServiceImpl.java
> +                () -> new RuntimeException("Can't found user: user")
too generic, use EntityNotFound or create your own UserNotFoundException

2024-02-11 18:37 UTC, okuzan commented on src/main/java/hanshyn/onlinebookstore/service/cart/ShoppingCartServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("Can]t found user: " + user));
same

2024-02-11 18:37 UTC, okuzan commented on src/main/java/hanshyn/onlinebookstore/service/cart/ShoppingCartServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("Can't found cart items by id :" + id));
entity not found

2024-02-11 18:37 UTC, okuzan commented on src/main/java/hanshyn/onlinebookstore/service/cart/ShoppingCartServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("Can't found user by id: " + user.getId()));
same

2024-02-12 10:37 UTC, Vasul-Pankiv approved these changes

2024-02-12 13:12 UTC, merged